language: rust

matrix:
  include:
    #- env: TARGET=x86_64-unknown-linux-gnu
    #  if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

    #- env: TARGET=riscv32imac-unknown-none-elf
    #  if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

    #- env: TARGET=x86_64-unknown-linux-gnu
    #  rust: beta
    #  if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

    #- env: TARGET=riscv32imac-unknown-none-elf
    #  rust: beta
    #  if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

    - env: TARGET=riscv32imac-unknown-none-elf
      rust: nightly
      if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
