[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "Semihosting for ARM Cortex-M processors"
documentation = "https://docs.rs/cortex-m-semihosting"
keywords = ["semihosting", "arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-semihosting"
repository = "https://github.com/japaric/cortex-m-semihosting"
version = "0.1.3"

[dependencies]
