language: rust

rust:
- nightly
- stable
- 1.31.0 # MSRV

env:
- TARGET=x86_64-unknown-linux-gnu
- TARGET=riscv32imac-unknown-none-elf
- TARGET=riscv64imac-unknown-none-elf

if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

matrix:
  exclude:
    - rust: stable
      env: TARGET=riscv64imac-unknown-none-elf
    - rust: 1.31.0 # MSRV
      env: TARGET=riscv64imac-unknown-none-elf


before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
